services:
  reverse-proxy:
    image: caddy:2.9-alpine
    container_name: reverse-proxy-dev
    ports:
      - "${PROXY_PORT:-3001}:80"
    volumes:
      - ./infra/reverse-proxy/Caddyfile.dev:/etc/caddy/Caddyfile:ro

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
      target: development
    image: backend-dev
    container_name: backend-dev
    volumes:
      - .:/app:cached
      - backend_node_modules:/app/node_modules
      - backend_pkg_node_modules:/app/packages/backend/node_modules
    develop:
      watch:
        - action: sync
          path: ./packages/backend/src
          target: /app/packages/backend/src
        - action: rebuild
          path: ./packages/backend/package.json

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
      target: development
    image: frontend-dev
    container_name: frontend-dev
    env_file:
      - .env
    volumes:
      - frontend_node_modules:/app/node_modules
      - frontend_pkg_node_modules:/app/packages/frontend/node_modules
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./packages/frontend/src
          target: /app/packages/frontend/src
        - action: sync
          path: ./packages/frontend/index.html
          target: /app/packages/frontend/index.html
        - action: rebuild
          path: ./packages/frontend/package.json

volumes:
  backend_node_modules:
  backend_pkg_node_modules:
  frontend_node_modules:
  frontend_pkg_node_modules:
