services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
      args:
        - PORT=${BACKEND_PORT}
    container_name: backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    container_name: frontend
    env_file:
      - .env
    environment:
      - API_PROXY_TARGET=http://backend:${BACKEND_PORT}/
      - NGINX_ENVSUBST_TEMPLATE_VARS=API_PROXY_TARGET
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge