upstream backend  { server backend:3000; }
upstream frontend { server frontend:80; }

server {
    listen 80;

    add_header X-Content-Type-Options  "nosniff" always;
    add_header X-Frame-Options         "DENY" always;
    add_header Referrer-Policy         "strict-origin-when-cross-origin" always;
    # add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload" always;

    location /api/ {
        proxy_pass http://backend;
        proxy_hide_header X-Content-Type-Options;
        proxy_hide_header X-Frame-Options;
        proxy_hide_header Content-Security-Policy;
        proxy_hide_header Referrer-Policy;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
    }

    location / {
        add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';" always;

        proxy_pass http://frontend;
        proxy_hide_header X-Content-Type-Options;
        proxy_hide_header X-Frame-Options;
        proxy_hide_header Content-Security-Policy;
        proxy_hide_header Referrer-Policy;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
    }
}
