name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/backend/**'
      - '.github/workflows/tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/backend/**'
      - '.github/workflows/tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci
        working-directory: packages/backend

      - name: Run tests
        run: npm test
        working-directory: packages/backend
